POST http://localhost:3000/api/message.add.reply
Accept: application/json

{
  "uid": "WuNFsCWb8ZgcIBmuIKsVIKbn1i72",
  "messageId": "l77gUXQYOquFel2XJBba",
  "reply": "This is a reply"
}

###
GET http://localhost:3000/api/message.list?uid=WuNFsCWb8ZgcIBmuIKsVIKbn1i72
Accept: application/json

###
GET http://localhost:3000/api/user.Info/wnsdyd21
Accept: application/json

###
GET http://localhost:3000/api/hello
Accept: application/json

###
POST http://localhost:3000/api/message.add
Accept: application/json

{
  "uid": "WuNFsCWb8ZgcIBmuIKsVIKbn1i72",
  "message": "tesddddt"
}

